### ISSUE TITLE
Publish package to a publicly available maven repository

### ISSUE THREAD

**Issue by astubbs** [whelk-io/asciidoc-template-maven-plugin#29]
The github repository is useful but it requires a login. Consider an easy alternative like jitpack - but you'd have to change your groupids.
Have you looked into publishing to maven central? It would make onboarding team members pain free. Setting up key access to the GitHub package repo is pretty rare and I'd rather not have that as a barrier.
Plus if anyone were to use this as a build step, it'd be a PITA for CI systems.

**Comment by zteater** [comment]
OK so I got the whelk.io domain registered with sonatype and have performed the initial release to Maven Central. It looks like it may take up to 2 hours before it is available in the search.

https://oss.sonatype.org/index.html#view-repositories;releases~browsestorage~/io/whelk/asciidoc/asciidoc-template-maven-plugin/1.0.8-RELEASE/asciidoc-template-maven-plugin-1.0.8-RELEASE.jar

**Comment by zteater** [comment]
After many trial and errors, finally got the action flow to publish to maven central when merging to master.

**Comment by zteater** [comment]
Available here in maven central: https://search.maven.org/artifact/io.whelk.asciidoc/asciidoc-template-maven-plugin
